(library
 (name stub_painter_lib)
 (modules stubPainter)
 (wrapped false)
 (libraries kicadsch)
 (flags
  (:standard -w -27)))

(tests
 (names test test_sexp_kicad_parser test_kicadsch_v8_parser test_real_v8_sch)
 (modules
  test
  test_sexp_kicad_parser
  test_kicadsch_v8_parser
  test_real_v8_sch)
 (libraries kicadsch ounit2 sexp_decode stub_painter_lib)
 (flags
  (:standard -w -27)))
